apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team-b
  name: team-b-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list", "create", "delete"]
