apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"team-a-binding","namespace":"team-a"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"team-a-role"},"subjects":[{"kind":"User","name":"team-a-user"}]}
    creationTimestamp: "2026-03-26T23:01:45Z"
    name: team-a-binding
    namespace: team-a
    resourceVersion: "20374"
    uid: ffd99e52-3397-4448-80c9-f42005461818
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: team-a-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: team-a-user
kind: List
metadata:
  resourceVersion: ""
